### ISSUE TITLE
Error: couldn’t find the specified template, please check again and try later

### ISSUE THREAD

**Issue by roamhacker** [shabegom/buttons#46]
My button stopped working, been working for a week or two and with a update a few days ago stopped. Here is the button:

```button
name Daily Template
type prepend template
action z New DNP
color blue
```
^button-zg7c

I have this connected to the nuclear reactor cooling system, its important that it works.

**Comment by shabegom** [comment]
@roamhacker I guess I'll help you.

Some questions. 
- Are you using both the internal Templates plugin **and** Templater? 
- Do you have different folders specified for each of those, or are they sharing the same folder? 
- Is this a Templater template or Core Templates Plugin template?

I feel like it has to do with my logic for finding the templates folder. It goes something like:

1. does the user have Core Templates enabled?
2. If Yes, what is the specified Templates folder?
3. Does the user have Templater installed?
4. If Yes what is the specified Templates folder?
5. If neither are enabled show error
6. If Templates is enabled, use that folder
7. If Templates isn't enabled but Templater is enabled, use that folder.
8. If the template can't be found show error

The solution would be to look in both folders for the template in case different folders are being used.

**Comment by shabegom** [comment]
this should be fixed in the next release

**Comment by roamhacker** [comment]
- I am using just Templater
- so just using templater, and it it is configured to a folder called f/templates)  (So folder called f, then a sub folder called templates)
- Templater template

I think these answers cover all the other questions.

**Comment by TiteiKo** [comment]
Hey there, I have the same issue, despite the v0.4.9 update. I only use Templater, core template is deactivated.

![image](https://user-images.githubusercontent.com/248372/119305826-89895980-bc69-11eb-8f82-88450c3373f4.png)

When opening obsidian I get the following error. I mention it because I don't get this error when Buttons is disabled.
![image](https://user-images.githubusercontent.com/248372/119306033-d9682080-bc69-11eb-9f16-e9ac579507e2.png)

Then when clicking the button:
![image](https://user-images.githubusercontent.com/248372/119306219-277d2400-bc6a-11eb-9afe-bd2d8a60939c.png)

**Comment by shabegom** [comment]
@TiteiKo this looks like a different bug than the one above! Will take a look.

**Comment by shabegom** [comment]
@TiteiKo please let me know of 0.4.10 fixes these errors (and your issue).

**Comment by TiteiKo** [comment]
Fixed, thank you 👍

**Comment by fabiannagel** [comment]
+1, I have the same issue. Just using Templater, Core Templates is disabled.
