### ISSUE TITLE
templater args don’t work with inline buttons yet

### ISSUE THREAD

**Issue by limanman77** [shabegom/buttons#61]
😊 When I use the inline button, it shows “templater args don’t work with inline buttons yet”.

obsidian v0.12.5
button v0.4.11

<img width="1194" alt="截屏2021-07-07 11 07 08" src="https://user-images.githubusercontent.com/26197836/124694745-73cbad00-df14-11eb-9ccd-dcc38311d854.png">
<img width="797" alt="截屏2021-07-07 11 02 09" src="https://user-images.githubusercontent.com/26197836/124694748-76c69d80-df14-11eb-96f6-ffd65776e241.png">

**Comment by shabegom** [comment]
This is tricky! When the templater snippet runs it does so in the note with the parent button and not the note with the inline button. 

I need some way to tell templater which note it should run in. Otherwise things can go wrong.

I suspect there is a way of doing this, but I need to chat with SV about the best approach. 

Thanks for reporting!
